---
title: "課堂練習模版"
author: "Hsu"
date: "2020-11-23"
output: output_format
params:
  id: "410683018"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
a <- c("L", "K", "Z")
a <- a[c(1,3)]
print(a)
```
```{r}
a <- c("L", "K", "Z")
a[-c(1,3)] # 不選1，3 
a <- a[-c(1,3)] # 刪去1, 3
```
#List的額外刪除方法,List多了使用NULL取代值來刪除，<-NULL (NULL是虛無，空的意思。)
```{r}
LL <- list('a', T, 183)
LL[c(1,3)] <- NULL 
print(LL) 
```
```{r}
a0 <- a <- c(John=178, Mary=170, Hanson=180)
names(a)  #按f1可以在右下角的help看到函數的使用方法

names(a) <- c("John", "Kate", "Hason")
names(a)

a <- a0
names(a)[[2]] <- "May"
names(a)
```
```{r}
a <- a[c(1,3)] # permanently change a

LL <- list("A", T, 17)
LL[[2]] <- NULL # permanently null the second element
LL
```
#On numeric class
```{r}
a <- c(2, 3, 5)
b <- c(4,-1, 3)
```
```{r}
a+b
a-b
a*b
a/b
```
```{r}
a %% b
# 相當於a/b的餘數
c(2%%4, 3%%(-1), 5%%3)

a ** b
```
#奇、偶數判斷
```{r}
sequenceNums <- c(11, 6, 8, 11, 12, 11, 3, 7, 10, 8)
print(sequenceNums)

sequenceNums %% 2 # 餘數為1則是奇數，0則是偶數
```
```{r}
set.seed(20389) #set.seed會固定抽出的排序
a2 <- sample(1:20,7)#sample 隨機
print(a2)
```
```{r}
b2 <- c(5,8,-1,7,6)
length(a2)
length(b2)
```
```{r}
b2
a2
a2+c(b2,5,8)
```
```{r}
# 狀況一: 堆疊一定倍數剛好一樣長
c(2,3)/c(-2,-13,10,22)
c(2,3,2,3)/c(-2,-13,10,22)
```

```{r}
paste0(
  c("我叫"), c("小明","小美")
)
paste0(
  c("我叫","我叫"), c("小明","小美")
)
```
```{r}
paste0(
  c("他叫","我叫"), c("小明","小美","大雄")
)
```

