---
title: "課堂練習模版"
author: "Hsu"
date: "2020-10-20"
output: output_format
params:
  id: "410683018"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code
```{r}
library(lubridate)
```

```{r}
tpeTime <- ymd_hms("2020-03-18 13:52:40",
        tz="Asia/Taipei")
```
```{r}
pgTime <- mdy_hms("Mar.18, 2020, 05:52:40", tz="Europe/Lisbon")
```

```{r}
ymd_hms(
c("2020-03-18 13:52:40","2020-03-11 03:12:40")
)
```
```{r}
ymd_hms("2020-03-11T06:56:17Z")
```
#type/class
```{r}
typeof(tpeTime)
class(tpeTime)
```
```{r}
tpeTime
print(tpeTime) #會出現時區的標記
cat(tpeTime)
```
```{r}
as.numeric(tpeTime)
```

```{r}
print(as.character(tpeTime))
cat(as.character(tpeTime))
```
#human tells computer
```{r}
tpeTime2 <- ymd_hms("2010-03-18 16:52:40",
        tz="Asia/Taipei")
pgTime2 <- mdy_hms("Mar.01, 2020, 03:52:40",
                  tz="Europe/Lisbon")
```
#computer tells human
```{r}
with_tz(tpeTime2,tzone="America/New_York")
```
```{r}
tpeTime3 <- with_tz(tpeTime2, tzone="America/New_York") #時區改變後文字描述的變化，不會改變電腦的時間記憶，也就是tpeYime2跟3在cat時秒數差距是一樣的
tpeTime2
tpeTime3
print(tpeTime2)
print(tpeTime3)
```
```{r}
pgTime3 <- 
  with_tz(pgTime2, tzone="America/New_York")

print(pgTime2)
print(pgTime3)
```
```{r}
tpeTime3
pgTime3
```
```{r}
# Method 2: pass as a character that fits ISO8601 date time description standard with tz onset specified
tpeTime_iso8601 <- format_ISO8601(tpeTime, usetz=T)
tpeTime_iso8601
```
```{r}
library(lubridate)

# Date/Time class
purchasingTime <- 
  ymd_hms("2020-03-31T13:40:55Z")

# character
location <- "一芳"
item <- "水果茶"
# numeric
quantity <- 2

mingsPurchase <-
  list(
    purchasingTime, 
    location, 
    quantity, 
    item
  )
print(mingsPurchase)
```
```{r}
a <- c(1,2,3)
print(a)
```

```{r}
mingsPurchase2 <-
  list(
    time = purchasingTime,
    'location' = location,
    "quantity" = quantity,
    `item name` = item
  )
print(mingsPurchase2)
```
```{r}
heights = c(
  mary=162,
  john=177,
  steve=180
)
print(heights)
```
```{r}
exampleList <- 
  list(
    4,
    "Mary",
    TRUE
  )
print(exampleList)
```
```{r}
example2 <- list(
    list(2,3),
    list(6,"Pat")
  )
#維持兩個元素，元素中才在包含其他子元素
print(example2)
```
```{r}
example2c <- c(
  c(2,5),
  c(4,6)
)
#如同c(2,5,4,6)，呈現四個元素的型態
print(example2c)
```

```{r}
# 「**2杯**」「**水果茶**」
item1 <- list(
  quantity=2,
  `item name`="水果茶"
)
# 「**1杯**」「**日月紅茶**」
item2 <- list(
  quantity=1,
  `item name`="日月紅茶"
)

mingsPurchase3 <-
  list(
    time = purchasingTime,
    location = location, #左邊是命名右邊是我要的值
    items=list(
      item1,
      item2
    )
  )

print(mingsPurchase3)
```

```{r}
student1 <-
  list(
    name = character(),
    id = character(),
    gmail = character(),
    googleClassroom =
      list(
        displayName = character()
      ),
    github =
      list(
        username = character(),
        repoUrl = character()
      ),
    homeworks = list(),
    exams = list(),
    list()
  )

names(student1) # 每個元素名稱
length(student1) # 元素個數
```

```{r}
str(student1, 1) # 第一層基本元素架構
```

```{r}
str(student1, 2) # 第一層基本元素架構
```

```{r}
hw1 <- list(
  date=ymd("2020-10-21"),
  grade=10
)
exam1 <- list(
  date=ymd("2020-10-28"),
  grade=50
)
student1 <-
  list(
    name = "Martin",
    id = "007",
    gmail = "mt@gm.ntpu.edu.tw",
    googleClassroom =
      list(
        displayName = "MT L"
      ),
    github =
      list(
        username = "tpemartin",
        repoUrl = "https://github.com/tpemartin/109-1-inclass-practice"
      ),
    homeworks = list(
      hw1
    ),
    exams = list(
      exam1
    ),
    list()
  )

str(student1, 2)
```

```{r}
categoryTemplate = 
  list(
    categoryName=character(),
    items = list(
    )
  )
```

```{r}
library(jsonlite) # 不少同學這行會有Error，還記得如何排除嗎？
toJSON(mingsPurchase3)
```

