---
title: "課堂練習模版"
author: "Hsu"
date: "2020-12-06"
output: output_format
params:
  id: "410683018"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
old_fct <- 
  factor(c("4以下","5-10","11-15"))
levels(old_fct) # 依序下的各類別名稱
```
```{r}
levels(old_fct) <- c("青少年", "幼兒", "兒童") #替換順序名稱
levels(old_fct)
old_fct
```
```{r}
old_fct2 <- 
  factor(c("4以下","5-10","11-15", "5-10"))
levels(old_fct2)
levels(old_fct2) <- c("4以下","5-10","11-15")   #要改變各類別排序得進行factor parsing的動作電腦才真的懂，以上是改變名稱
old_fct2
```
#改變類別稱呼還有一個應用就是進行「類別整併」
```{r}
set.seed(2020)
ages_chr <- sample(c("4以下","5-9","10-14", "15-19"), 20, replace=T)
ages_chr
```
```{r}
ages_fctBy10 <- ages_fctBy5 <- 
  factor(
    ages_chr,
    levels = c("4以下","5-9","10-14", "15-19")
  )

levels(ages_fctBy5)
table(ages_fctBy5)
```
```{r}
levels(ages_fctBy10) <- c("10以下", "10以下", "10以上", "10以上")
table(ages_fctBy5)
```
```{r}
head(ages_fctBy5)
head(ages_fctBy10)
```
#增加資料
```{r}
#新的值無需進行factor parsing, 直接以字串值來增加即可
set.seed(2020)
ages_chr <- sample(c("4以下","5-9","10-14", "15-19"), 10, replace=T)
ages_chr
```
```{r}
data_fct <- factor(ages_chr)
length(data_fct)
```
```{r}
data_fct[[11]] <- c("10-14")
data_fct
data_fct[c(12, 13)] <- c("5-9","15-19")
data_fct
```
#要先讓電腦知道有新類別的存在才能新增資料
```{r}
levels(data_fct) 
data_fct[[14]] <- "20-24" #此類別尚不存在
data_fct[[14]]
```
```{r}
levels(data_fct)[[5]] <- "20-24"
levels(data_fct)
data_fct[[14]] <- "20-24"
data_fct
```
#若要新增的類別想放levels現有排序內，可先新增類別在後，加完資料後, 再進行factor parsing動作來修正類別排序
```{r}
ages_chr <- sample(c("5-9","10-14", "15-19"), 8, replace=T)
data_fct <- factor(ages_chr,
                   levels = c("5-9","10-14", "15-19"),
                   ordered = T)
# 新增類別
levels(data_fct)[c(4, 5)] <- c("20-24", "4以下")
# 新增資料
data_fct[c(9, 10, 11, 12)] <- c("20-24", "10-14", "15-19", "4以下")
# factor parsing修正排序
data_fct <- factor(
  data_fct,
  levels = c("4以下", "5-9","10-14", "15-19", "20-24")
)
data_fct
```
#增加類別資料千萬不能用直接用c( )進行recursive concatenate:
```{r}
# 非類別資料
numVect <- c(2, 5, 7)
# 新增c(6, 10)
numVect <- c(numVect, c(6,10))
numVect
```
```{r}
# 類別資料
fctVector <- factor(c("a","b", "c", "a"))
# 新增 'a', 'c'
fctVector
fctVector <- c(fctVector, c('a','c'))
fctVector   #c是用電腦儲存的type職進行堆疊
```
#使用list
兩個相同class vector的堆疊：
c( )堆疊
只會攜帶元素的儲存值及一小部份的原素屬性（attributes）如names（元素名稱）。
不會保留各元素的向量層次區隔，會維持atomic vector型態。
```{r}
a <- c(Mary=178, Jack=165)
attr(a, "family") <- "Johnson"
attributes(a)

b <- c(Ben=170, David=172)
attr(b, "family") <- "Jenson"
attributes(b)

a_b <- c(a, b)
attributes(a_b)
```
#list( )堆疊
會攜帶元素的所有屬性（attributes）。且保留各元素的向量層次，形成各自區隔的元素值
```{r}
list_ab <- list(a, b)
list_ab
attributes(list_ab)
attributes(a)
attributes(b)
```
```{r}
#若list裡元素為相同class, 可使用unlist( )打破各自元素區隔而整併成一個atomic vector
unlist_ab <- unlist(list_ab)
unlist_ab
attributes(unlist_ab)
```
```{r}
fct_a <- factor(c('a','d','e'))
fct_b <- factor(c("a","e","j"))

list_ab <- 
  list(fct_a, fct_b)  #屬性保留
list_ab #list概念

unlist(list_ab) -> fct_ab

fct_ab
```

