---
title: "課堂練習模版"
author: "Hsu"
date: "2020-10-07"
output: output_format
params:
  id: "410683018"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
a <- 15 # 變數設定
b <- a # 呼叫a的值，用來設定變數b的值，相當於 b <- 15
y <- 22
c <- y
```
```{r}
myName <- "Mary"
```
```{r}
length(myName) # 查看物件本身代表幾個值。
```
```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```
```{r}
num1 <- 5
num2 <- c(5)
```
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```
```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

```{r}
c(5,7)
```
```{r}
c(T,TRUE,F,FALSE)
```
```{r}
num1<-5 # 非整數
num2<-5L # 整數

num1Vector<-c(5,6,7)
num2Vector<-c(5L,6L,7L)
```
```{r}
object.size(num1)
object.size(num2)
object.size(num1Vector)
object.size(num2Vector)
```
```{r}
dialogue <- c('小明說："明天不用上課。"',
               '小花說："真的嗎？"')

dialogue # 顯示原始值的內容（含輸入時的引號）
cat(dialogue, sep="\n") # 顯示給人類看（含存出來）的值，sep="\n", 不同元素換行陳列。
#writeLines(dialogue, "conversation.txt") # cat顯示的正是存出來樣貌。
```

```{r}
context <- "老師說換行要寫\\n" # 請依下列情境輸入
cat(context)
```

