---
title: "課堂練習模版"
author: "Hsu"
date: "2020-10-14"
output: output_format
params:
  id: "410683018"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
"\u0928\u092e\u0938\u094d\u0924\u0947 \u0926\u0941\u0928\u093f\u092f\u093e"
```
```{r}
num <- c(1.5, 2, 3)
int <- c(1L, 3L, -2L)
char <- c("1.5","2","3")
logi <- c(T,T,F)

typeof(num)
typeof(int)
typeof(char)
typeof(logi)
```

```{r}
class(num)
class(int)
class(char)
class(logi)
```
```{r}
1+1.5
```
#caracter形式
```{r}
# 10位學生的主系
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')

typeof(majors10_char)
class(majors10_char)
```
#factor
```{r}
majors10_factor <- factor(majors10_char)
typeof(majors10_factor)
class(majors10_factor)
```
#將物件裡的數字還原出來
```{r}
as.numeric("1")
```
#要改變物件值時要記得回存
```{r}
a <- "1"
as.numeric(a)->a #將環後的數字再回存回a
a+4
```
#factor(r的分類從1開始，以此類推)
```{r}
majors10_char
majors10_factor
```
```{r}
as.integer(majors10_factor) 
```
```{r}
a <- factor(c("一","二","三"))
a
```
```{r}
stringInteger <- c("1","2","-11")
class(stringInteger) # 無法進行數值運算因為他是字串
stringInteger+2
```
```{r}
trueInteger <- as.integer(stringInteger)
class(trueInteger) # 可以進行數值運算因為trueinterger為數值
typeof(trueInteger)
trueInteger+2
```
